# Generated by Django 2.2.2 on 2019-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('facultyLec', models.CharField(max_length=255, null=True)),
                ('departmentLec', models.CharField(max_length=255, null=True)),
                ('priorityNumber', models.IntegerField(default=1)),
                ('mon_0', models.BooleanField(default=True)),
                ('mon_1', models.BooleanField(default=True)),
                ('mon_2', models.BooleanField(default=True)),
                ('tue_0', models.BooleanField(default=True)),
                ('tue_1', models.BooleanField(default=True)),
                ('tue_2', models.BooleanField(default=True)),
                ('wed_0', models.BooleanField(default=True)),
                ('wed_1', models.BooleanField(default=True)),
                ('wed_2', models.BooleanField(default=True)),
                ('thu_0', models.BooleanField(default=True)),
                ('thu_1', models.BooleanField(default=True)),
                ('thu_2', models.BooleanField(default=True)),
                ('fri_0', models.BooleanField(default=True)),
                ('fri_1', models.BooleanField(default=True)),
                ('fri_2', models.BooleanField(default=True)),
                ('sat_0', models.BooleanField(default=False)),
                ('sat_1', models.BooleanField(default=False)),
                ('sat_2', models.BooleanField(default=False)),
            ],
        ),
    ]
