# Generated by Django 2.2.2 on 2019-07-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LectureStartTime', models.TimeField(verbose_name='Conversation Time')),
                ('LectureCloseTime', models.TimeField(verbose_name='Conversation Time')),
                ('AllowDailyBrkTime', models.BooleanField(default=True)),
                ('DailyBrkStartTime', models.TimeField(verbose_name='Conversation Time')),
                ('DailyBrkDuration', models.IntegerField(default=30)),
                ('MuslimWeekPrayer', models.BooleanField(default=True)),
                ('MuslimPrayStart', models.TimeField(verbose_name='Conversation Time')),
                ('MuslimPrayDuration', models.IntegerField(default=60)),
                ('LecMaxCosPerSem', models.IntegerField(default=3)),
                ('LecMaxClassPerDay', models.IntegerField(default=2)),
                ('LecMinBtwClasses', models.IntegerField(default=30)),
                ('StuMaxClassPerDay', models.IntegerField(default=2)),
                ('StuMinBtwClasses', models.IntegerField(default=30)),
            ],
        ),
    ]
