# Generated by Django 2.2.2 on 2019-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconstraints',
            name='visitingLecturer',
            field=models.BooleanField(default=True),
        ),
    ]
