# Generated by Django 2.2.2 on 2019-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0002_userconstraints_visitinglecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconstraints',
            name='AssignSaturdays',
            field=models.BooleanField(default=True),
        ),
    ]
