# Generated by Django 2.2.2 on 2019-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0003_userconstraints_assignsaturdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconstraints',
            name='AssignSaturdays',
            field=models.BooleanField(default=False),
        ),
    ]
