# Generated by Django 2.2.2 on 2019-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0004_auto_20190815_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconstraints',
            name='restrictVisiting',
            field=models.BooleanField(default=True),
        ),
    ]
