# Generated by Django 2.2.2 on 2019-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionType', models.BooleanField(default=True)),
                ('currentsession', models.CharField(max_length=64)),
                ('currentsemestername', models.CharField(max_length=64)),
                ('currentsemestertype', models.IntegerField(default=1)),
            ],
        ),
    ]
