# Generated by Django 2.2.2 on 2019-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='currentsemestername',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
