# Generated by Django 2.2.2 on 2019-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('type', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=50)),
                ('reservedLevel', models.CharField(max_length=2048, null=True)),
                ('reservedFaculty', models.CharField(max_length=2048, null=True)),
                ('reservedDepartment', models.CharField(max_length=2048, null=True)),
                ('reservedDays', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
