# Generated by Django 2.2.2 on 2019-06-30 00:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Mondays'), ('Tue', 'Tuesdays'), ('Wed', 'Wednesdays'), ('Thu', 'Thurdays'), ('Fri', 'Fridays'), ('Sat', 'Saturdays')], max_length=23),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedLevel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], max_length=19),
        ),
    ]
