# Generated by Django 2.2.2 on 2019-06-30 16:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0002_auto_20190630_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Mondays'), ('Tue', 'Tuesdays'), ('Wed', 'Wednesdays'), ('Thu', 'Thurdays'), ('Fri', 'Fridays'), ('Sat', 'Saturday')], max_length=23),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedDepartment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT005', 'Electrical & Electronics Engineering'), ('DPT006', 'Mechanical Engineering'), ('DPT007', 'Telecommunications Engineering'), ('DPT008', 'Civil Engineering'), ('DPT009', 'Petroleum Engineering'), ('DPT013', 'Law LLB'), ('DPT014', 'Business Law LLB'), ('DPT015', 'Private and Public Law LLB')], default='', max_length=62),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FAC01', 'Faculty of Engineering'), ('FAC20', 'Faculty of Law')], default='', max_length=11),
            preserve_default=False,
        ),
    ]
