# Generated by Django 2.2.2 on 2019-07-02 20:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0004_auto_20190630_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDepartment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT005', 'Electrical & Electronics Engineering'), ('DPT006', 'Mechanical Engineering'), ('DPT007', 'Telecommunications Engineering'), ('DPT008', 'Civil Engineering'), ('DPT009', 'Petroleum Engineering')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FAC01', 'Faculty of Engineering'), ('FAC20', 'Faculty of Law')], max_length=2048),
        ),
    ]
