# Generated by Django 2.2.2 on 2019-07-03 12:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0006_auto_20190703_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FAC01', 'Engineering'), ('FAC27', 'Law')], max_length=2048),
        ),
    ]
