# Generated by Django 2.2.2 on 2019-07-03 20:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0010_auto_20190703_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDays',
            field=multiselectfield.db.fields.MultiSelectField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedDepartment',
            field=multiselectfield.db.fields.MultiSelectField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedLevel',
            field=multiselectfield.db.fields.MultiSelectField(max_length=2048),
        ),
    ]
