# Generated by Django 2.2.2 on 2019-07-04 14:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0011_auto_20190703_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Mondays'), ('Tue', 'Tuesdays'), ('Wed', 'Wednesdays'), ('Thu', 'Thurdays'), ('Fri', 'Fridays'), ('Sat', 'Saturday')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedDepartment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT034', 'Civil Engineering'), ('DPT035', 'Mechanical Engineering'), ('DPT036', 'Telecommunications Engineering'), ('DPT037', 'Petroleum Engineering'), ('DPT038', 'Electrical & Electronics Engineering'), ('DPT039', 'Law LLB')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FAC01', 'Engineering'), ('FAC36', 'Law')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedLevel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], max_length=2048),
        ),
    ]
