# Generated by Django 2.2.2 on 2019-07-06 12:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues_mgt', '0012_auto_20190704_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservedDepartment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT034', 'Civil Engineering'), ('DPT035', 'Mechanical Engineering'), ('DPT036', 'Telecommunications Engineering'), ('DPT037', 'Petroleum Engineering'), ('DPT038', 'Electrical & Electronics Engineering')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservedFaculty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FAC01', 'Engineering')], max_length=2048),
        ),
    ]
