# Generated by Django 2.2.2 on 2019-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('faculty', models.CharField(max_length=10)),
                ('officer', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
