# Generated by Django 2.2.2 on 2019-07-03 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(db_column='faculty', on_delete=django.db.models.deletion.CASCADE, to='faculty_mgt.Faculty', to_field='code'),
        ),
    ]
