# Generated by Django 2.2.2 on 2019-07-03 16:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0004_auto_20190703_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT025', 'Civil Engineering'), ('DPT026', 'Mechanical Engineering'), ('DPT027', 'Telecommunications Engineering')], max_length=2048),
        ),
    ]
