# Generated by Django 2.2.2 on 2019-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0007_auto_20190704_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.CharField(max_length=2048),
        ),
    ]
