# Generated by Django 2.2.2 on 2019-07-06 13:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0009_auto_20190706_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPT001', 'Computer Engineering'), ('DPT034', 'Civil Engineering'), ('DPT035', 'Mechanical Engineering'), ('DPT036', 'Telecommunications Engineering'), ('DPT037', 'Petroleum Engineering'), ('DPT038', 'Electrical & Electronics Engineering')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LEC0001', 'Mr. A'), ('LEC0013', 'Mr. B'), ('LEC0014', 'Mr. C'), ('LEC0015', 'Mr. D'), ('LEC0016', 'Mr. E'), ('LEC0017', 'MR. F'), ('LEC0018', 'Mr. G'), ('LEC0019', 'Mr. K'), ('LEC0020', 'Mr. M'), ('LEC0021', 'Mr. N')], max_length=2048),
        ),
    ]
