# Generated by Django 2.2.2 on 2019-07-13 07:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0010_auto_20190706_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LEC0001', 'Mr. A'), ('LEC0013', 'Mr. B'), ('LEC0014', 'Mr. C'), ('LEC0015', 'Mr. D'), ('LEC0016', 'Mr. E'), ('LEC0017', 'MR. F'), ('LEC0018', 'Mr. G'), ('LEC0019', 'Mr. K'), ('LEC0020', 'Mr. M'), ('LEC0021', 'Mr. N'), ('LEC0022', 'Mr. Z'), ('LEC0023', 'Mr. AB'), ('LEC0024', 'Mr. AP'), ('LEC0025', 'Mr. OP'), ('LEC0026', 'Mr. BM'), ('LEC0027', 'Mr. KN'), ('LEC0028', 'Mr. AL'), ('LEC0029', 'Mr. EG'), ('LEC0030', 'Mr. PL'), ('LEC0031', 'Mr. AJ'), ('LEC0032', 'Mr. ET'), ('LEC0033', 'Mr. KL'), ('LEC0034', 'Mr. EM'), ('LEC0035', 'MR. KP'), ('LEC0036', 'MR. KQ'), ('LEC0037', 'Mr. DP')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
