# Generated by Django 2.2.2 on 2019-08-10 23:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0011_auto_20190713_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=multiselectfield.db.fields.MultiSelectField(max_length=2048),
        ),
    ]
