# Generated by Django 2.2.2 on 2019-08-12 21:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0013_auto_20190812_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LEC0001', 'David Mark'), ('LEC0002', 'Angela Kelly'), ('LEC0003', 'Eleanar james'), ('LEC0004', 'Blessing Okorikoko'), ('LEC0005', 'Dr. Dioha Mike'), ('LEC0006', 'Blessing Okorikoko')], max_length=2048),
        ),
    ]
