# Generated by Django 2.2.2 on 2019-08-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgt', '0016_auto_20190815_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='preferedtime',
            new_name='subjecttype',
        ),
    ]
