# Generated by Django 2.2.2 on 2019-07-05 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues_mgt', '0012_auto_20190704_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('session', models.CharField(max_length=10)),
                ('gendate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('semestername', models.CharField(max_length=10, unique=True)),
                ('semestertype', models.IntegerField(default=1)),
                ('totalgen', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TablesGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=255, unique=True)),
                ('totalenrol', models.IntegerField(default=0)),
                ('starttime', models.TimeField(verbose_name='Conversation Time')),
                ('endtime', models.TimeField(verbose_name='Conversation Time')),
                ('lecturers', models.CharField(max_length=2048)),
                ('lectureday', models.CharField(max_length=3)),
                ('code', models.ForeignKey(db_column='code', default=None, on_delete=django.db.models.deletion.CASCADE, to='tablegenerator.TableRegister', to_field='code')),
                ('venue', models.ForeignKey(db_column='venue', default=None, on_delete=django.db.models.deletion.CASCADE, to='venues_mgt.Venue', to_field='code')),
            ],
        ),
    ]
