# Generated by Django 2.2.2 on 2019-08-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablegenerator', '0003_auto_20190815_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesgenerated',
            name='venue',
            field=models.ForeignKey(db_column='venue', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='venues_mgt.Venue', to_field='code'),
        ),
    ]
