# Generated by Django 2.2.2 on 2019-08-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments_mgt', '0004_auto_20190703_1254'),
        ('tablegenerator', '0004_auto_20190816_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesgenerated',
            name='department',
            field=models.ForeignKey(db_column='department', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments_mgt.Department', to_field='code'),
        ),
    ]
