# Generated by Django 2.2.2 on 2019-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablegenerator', '0005_tablesgenerated_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableregister',
            name='semestername',
            field=models.CharField(max_length=10),
        ),
    ]
