# Generated by Django 2.2.2 on 2019-07-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments_mgt', '0004_auto_20190703_1254'),
        ('courses_mgt', '0007_auto_20190704_1457'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_code',
            field=models.ForeignKey(db_column='course_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='courses_mgt.Course', to_field='code'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='department',
            field=models.ForeignKey(db_column='department', default=None, on_delete=django.db.models.deletion.CASCADE, to='departments_mgt.Department', to_field='code'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semesterName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semesterType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
