# Generated by Django 2.2.2 on 2019-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20190704_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
