# Generated by Django 2.2.2 on 2019-08-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_mgt', '__first__'),
        ('departments_mgt', '0004_auto_20190703_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1, unique=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('LecMaxCosPerSem', models.IntegerField(default=1)),
                ('LecMaxCosPerDay', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('departmentLec', models.ForeignKey(db_column='departmentLec', default=None, on_delete=django.db.models.deletion.CASCADE, to='departments_mgt.Department', to_field='code')),
                ('facultyLec', models.ForeignKey(db_column='facultyLec', default=None, on_delete=django.db.models.deletion.CASCADE, to='faculty_mgt.Faculty', to_field='code')),
                ('priorityNumber', models.ForeignKey(db_column='priorityNumber', default=None, on_delete=django.db.models.deletion.CASCADE, to='lecturers_mgt.staffTypes', to_field='type')),
            ],
        ),
    ]
