# Generated by Django 2.2.2 on 2019-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers_mgt', '0002_auto_20190812_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftypes',
            name='LecMaxCosPerDay',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='stafftypes',
            name='LecMaxCosPerSem',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stafftypes',
            name='designation',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
