# Generated by Django 2.2.2 on 2019-08-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers_mgt', '0003_auto_20190812_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturers',
            name='fri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturers',
            name='mon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturers',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturers',
            name='thu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturers',
            name='tue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturers',
            name='wed',
            field=models.BooleanField(default=True),
        ),
    ]
