# Generated by Django 2.2.2 on 2019-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers_mgt', '0004_auto_20190812_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturers',
            name='friFrom',
            field=models.TimeField(default='08:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='friTo',
            field=models.TimeField(default='18:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='monFrom',
            field=models.TimeField(default='08:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='monTo',
            field=models.TimeField(default='18:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='satFrom',
            field=models.TimeField(default='00:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='satTo',
            field=models.TimeField(default='00:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='thuFrom',
            field=models.TimeField(default='08:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='thuTo',
            field=models.TimeField(default='18:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='tueFrom',
            field=models.TimeField(default='08:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='tueTo',
            field=models.TimeField(default='18:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='wedFrom',
            field=models.TimeField(default='08:00', verbose_name='Conversation Time'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='wedTo',
            field=models.TimeField(default='18:00', verbose_name='Conversation Time'),
        ),
    ]
