# Generated by Django 2.2.2 on 2019-08-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers_mgt', '0005_auto_20190812_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturers',
            name='visiting',
            field=models.BooleanField(default=False),
        ),
    ]
